version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    expose:
      - "9000"  # PHP-FPM listens on this port
    command: ["php-fpm"] 

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secret123'
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD: 'secret123'
      MYSQL_DATABASE: 'haarlem_festivaldb'
    volumes:
      - mysqldata:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
    restart: unless-stopped

volumes:
  mysqldata: {}
